name: complex

on: push

jobs:
        job1:
                name: Ubuntu
                runs-on: ubuntu-latest
                steps:
                - name: Print datetime
                  run: date
        job2:
                name: Windows
                runs-on: windows-latest
                steps:
                - name: Print datetime
                  run: Get-Date
        job3:
                name: MacOS
                runs-on: macos-latest
                steps:
                - name: Print datetime
                  run: date
        job4:
                name: Depending-Job
                runs-on: ubuntu-18.04
                needs: [job1, job2, job3]
                steps:
                - name: Print datetime
                  run: date
