name: upload_artifact

on: push

env:
        FILE_NAME: ho_CWENO_bt

jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                        - name: checkout
                          uses: actions/checkout@v2
                          with:
                                  repository: SvoONs/higher_order_CWENO_boundary_treatment@main
                                  path: ./${{ env.FILE_NAME }}
                        - name: upload
                          uses: actions/upload-artifact@v2
                          with:
                                  name: ${{ env.FILE_NAME }}
                                  path: .
